#ifndef VALUUTTAMUUNNINDLL_GLOBAL_H
#define VALUUTTAMUUNNINDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VALUUTTAMUUNNINDLL_LIBRARY)
#  define VALUUTTAMUUNNINDLL_EXPORT Q_DECL_EXPORT
#else
#  define VALUUTTAMUUNNINDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // VALUUTTAMUUNNINDLL_GLOBAL_H
